const menu = [
    {
      id: 1,
      title: 'Hamburguesa de 1lb',
      category: 'hamburguesas',
      price: 44.99,
      img: './images/item-1.jpeg',
      desc: `Hamburguesa hecha con 4 tortas de 1/4lb de carné angus, con queso derretido, cebolla caramelizada, tocino y pan de mantequilla`,
    },
    {
      id: 2,
      title: 'Papotas Fastclub',
      category: 'aperitivo',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `Entrada de papas sin aceite y grasa, con queso y tocino añadido, preparadas con freidora de aire`,
    },
    {
      id: 3,
      title: 'Mini milkshake',
      category: 'bebidas',
      price: 4.99,
      img: './images/item-3.jpeg',
      desc: `Bebida fría hecha con café y leche, con topping de crema`,
    },
    {
      id: 4,
      title: 'Panini',
      category: 'hamburguesas',
      price: 19.99,
      img: './images/item-4.jpeg',
      desc: `Sandwich de pan submarino con jamón y queso o embutidos con salsa barbacoa`,
    },
    {
      id: 5,
      title: 'Waffle Fries',
      category: 'aperitivo',
      price: 14.99,
      img: './images/item-5.jpeg',
      desc: `Entrada de papas con forma de waffle, acompañadas de queso y tocino, preparadas con freidora de aire`,
    },
    {
      id: 6,
      title: 'Choco Boom',
      category: 'bebidas',
      price: 14.99,
      img: './images/item-6.jpeg',
      desc: `Bebida fría hecha con leche y crema, con añadido de jarabe de chocolate`,
    },
    {
      id: 7,
      title: 'Hamburguesa universitaria',
      category: 'hamburguesas',
      price: 9.99,
      img: './images/item-7.jpeg',
      desc: `Hamburguesa pequeña con carne angus, con añadido de aderezo de ají chipotle, queso cheddar y tocino ahumado`,
    },
    {
      id: 8,
      title: 'Costillas BBQ',
      category: 'aperitivo',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `Costillitas de cerdo al horno acompañadas con salsa barbacoa`,
    },
    {
      id: 9,
      title: 'Frappe Clásico',
      category: 'bebidas',
      price: 9.99,
      img: './images/item-9.jpeg',
      desc: `Bebida de fría de café y leche con crema batida y topping de canela o chocolate`,
    },
  ];
  export default menu;
